ordering_project/config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from core.views import main_page


urlpatterns = [

    # Apps
    path(
        route='',
        view=main_page,
        name='home_page'
    ),
    path(
        route='users/',
        view=include('users.urls', namespace='users'),
    ),
    # path(
    #     route='categories/',
    #     view=include(...),
    #     name='categories'
    # ),
    # path(
    #     route='products/',
    #     view=include(...),
    #     name='products'
    # ),
    # path(
    #     route='orders/',
    #     view=include(...),
    #     name='orders'
    # ),

    # API


    # Core
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()

ordering_project/ordering/users/urls.py
from django.urls import path

from .views import (
    users_list_view,
    register_view,
    login_view,
    logout_view,
    user_detail_view,
    user_detail_delete_view
)


app_name = 'users'

urlpatterns = [
    path(
        route='',
        view=users_list_view,
        name='list'
    ),
    path(
        route='profile/<int:pk>/',
        view=user_detail_view,
        name='profile'
    ),
    path(
        route='profile/<int:pk>/delete',
        view=user_detail_delete_view,
        name='profile_delete'
    ),

    path(
        route='register/',
        view=register_view,
        name='register'
    ),
    path(
        route='login/',
        view=login_view,
        name='login'
    ),
    path(
        route='logout/',
        view=logout_view,
        name='logout'
    )
]

ordering_project/ordering/addresses/models.py
from django.db import models

# Create your models here.

ordering_project/ordering/categories/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
    )

ordering_project/ordering/core/models.py
from django.db import models

# Create your models here.

ordering_project/ordering/orders/models.py
from django.db import models

# Create your models here.

ordering_project/ordering/products/models.py
from django.db import models

# Create your models here.

ordering_project/ordering/users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class UserManager(BaseUserManager):
    def create_user(self, email='', username='', password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')
        if not password:
            raise ValueError('Users must have a password')

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(email, username, password)
        user.is_admin = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True
    )
    username = models.CharField(
        max_length=255,
        unique=True
    )
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    date_of_birth = models.DateField(null=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return f'{self.email}'

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

ordering_project/ordering/users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError

from .models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'username')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError('Passwords dont match')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = '__all__'


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def save(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        user = authenticate(username=email, password=password)
        return user

ordering_project/ordering/addresses/views.py
from django.shortcuts import render

# Create your views here.

ordering_project/ordering/categories/views.py
from django.shortcuts import render

# Create your views here.

ordering_project/ordering/core/views.py
from django.shortcuts import render


def main_page(request):
    if request.method == 'GET':
        return render(request, 'home_page.html')

ordering_project/ordering/orders/views.py
from django.shortcuts import render

# Create your views here.

ordering_project/ordering/products/views.py
from django.shortcuts import render

# Create your views here.

ordering_project/ordering/users/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from rest_framework import status

from .forms import UserCreationForm, UserLoginForm
from .models import User


@login_required(login_url='users:login')
def users_list_view(request):
    if request.method == 'GET':
        users = User.objects.all()
        return render(request, 'users/users_list.html', {'users': users})


@login_required(login_url='users:login')
def user_detail_view(request, pk):
    if request.method == 'GET':
        data = {}
        if request.user.pk == pk or request.user.is_admin:
            user = get_object_or_404(User, pk=pk)
            data['user'] = user
            return render(request, 'users/user_detail.html', data)
        else:
            messages.error(request, 'Cant access another profiles info')
            return redirect('users:list')


@login_required(login_url='users:login')
def user_detail_delete_view(request, pk):
    if request.method == 'GET':
        if request.user.pk == pk or request.user.is_admin:
            user = get_object_or_404(User, pk=pk)
            user.delete()
            return redirect('users:list')
        else:
            messages.error(request, 'Cant delete another user')
            return redirect('users:list')


def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account has been created for {username}')
            return redirect('users:login')

    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = form.save()

            if user is not None:
                login(request, user)
                messages.success(request, f'Successfully logged in')

                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect('home_page')

            else:
                messages.error(request, 'Invalid username or password')
        else:
            messages.error(request, 'Invalid username or password')
    else:
        form = UserLoginForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)

    messages.success(request, f'Successfully logged out')
    return redirect('users:login')

ordering_project/ordering/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {% for field in form %}
                <tr class="fieldWrapper">
                    {{ field.errors }}
                    <th>{{ field.label_tag }}</th> <td>{{ field }} </td>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </tr>
            {% endfor %}

            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}

            <tr><td><input type="submit" value="Submit"></td></tr>
        </table>
    </form>
</div>

{% endblock content %}

ordering_project/ordering/templates/users/register.html
{% extends "base.html" %}

{% block content %}
<div>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {% for field in form %}
                <tr class="fieldWrapper">
                    {{ field.errors }}
                    <th>{{ field.label_tag }}</th> <td>{{ field }} </td>
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </tr>
            {% endfor %}
            <tr><td><input type="submit" value="Submit"></td></tr>
        </table>
    </form>
</div>

{% endblock content %}

ordering_project/ordering/templates/users/user_detail.html
{% extends "base.html" %}

{% block content %}
<div>
    User:
    <div id="user_id">&emsp; id: {{user.pk}}</div>
    <div id="username">&emsp; username: {{user.username}}</div>
    <div id="email">&emsp; email: {{user.email}}</div>
    <div>&emsp; first name: {{user.first_name}}</div>
    <div>&emsp; last name: {{user.last_name}}</div>
    <div>&emsp; birthday: {{user.date_of_birthday}}</div>

    <a href="{% url 'users:profile_delete' user.pk %}">Delete</a>
</div>
{% endblock content %}

ordering_project/ordering/templates/users/users_list.html
{% extends "base.html" %}

{% block content %}
{% for user in users%}
    <div>
        User:
        <div>&emsp; username: <a href="{% url 'users:profile' user.pk %}">{{user.username}}</a></div>
        <div>&emsp; email: {{user.email}}</div>
    </div>
{% endfor %}
{% endblock content %}